const image=(name)=>'assets/polar/'+name;
const products=[
 {id:'milky-pie',name:'Milky Pie',kind:'Vanilla frozen dessert in a chocolate coating',category:'lollies',price:15,img:image('product__0005_Stick-Lolly-Milky-Pie-Wrapper-768x910-1.png'),tag:'A favourite'},
 {id:'strawberry-sensation',name:'Strawberry Sensation',kind:'Strawberry flavoured ice',category:'lollies',price:10,img:image('product__0002_Stick-Lolly-Strawberry-Sensation-Wrapper-768x910-1.png')},
 {id:'three-in-one',name:'Three in One',kind:'Orange and raspberry ice dipped in chocolate',category:'lollies',price:null,img:image('product__0001_Stick-Lolly-Three-in-One-Wrapper-768x910-1.png'),tag:'Popular'},
 {id:'choc-overload',name:'Choc Overload',kind:'Chocolate frozen dessert',category:'lollies',price:12,img:image('product__0019_Stick-Lolly-Chocolate-Overload-Wrapper-768x910-1.png')},
 {id:'berry-blaze',name:'Berry Blaze',kind:'Berry flavoured ice lolly',category:'lollies',price:7,img:image('product__0021_Stick-Lolly-BerryBlaze-Wrapper-768x910-1.png')},
 {id:'bubblegum',name:'Bubblegum',kind:'Bubblegum frozen dessert',category:'lollies',price:null,img:image('product__0020_Stick-Lolly-Bubblegum-Wrapper-768x910-1.png')},
 {id:'lemonlik',name:'Lemonlik',kind:'Lemon and lime flavoured ice lolly',category:'lollies',price:7,img:image('product__0008_Stick-Lolly-Lemonlik-Wrapper-768x910-1.png')},
 {id:'tropaz',name:'Tropaz',kind:'Pineapple, passion fruit and banana ice',category:'lollies',price:7,img:image('product__0000_Stick-Lolly-Tropaz-Lolly-Wrapper-768x910-1.png')},
 {id:'mr-apple',name:'Mr Apple',kind:'Apple flavoured ice',category:'lollies',price:7,img:image('product__0004_Stick-Lolly-Mr-Apple-Wrapper-768x910-1.png')},
 {id:'polar-split',name:'Polar Split',kind:'Vanilla dessert with orange flavoured ice',category:'lollies',price:null,img:image('product__0003_Stick-Lolly-Split-Wrapper-768x910-1.png')},
 {id:'mango-bango',name:'Mango Bango',kind:'Fruit flavoured ice',category:'lollies',price:7,img:image('product__0006_Stick-Lolly-Mango-Bango-Wrapper-768x910-1.png')},
 {id:'lichilik',name:'LichiLik',kind:'Apple, pear and litchi ice',category:'lollies',price:7,img:image('product__0007_Stick-Lolly-Lichilik-Wrapper-768x910-1.png')},
 {id:'viva',name:'Viva',kind:'Vanilla frozen dessert dipped in chocolate',category:'lollies',price:null,img:image('product__0025_Layer-0.png')},
 {id:'banana-berry',name:'Banana Berry',kind:'Banana and strawberry frozen dessert',category:'lollies',price:null,img:image('product__0023_Stick-Lolly-Bananaberry-Wrapper-768x910-1.png')},
 {id:'banana-split',name:'Banana Split',kind:'Chocolate and banana frozen dessert',category:'lollies',price:null,img:image('product__0022_Stick-Lolly-Banana-Split-Wrapper-768x910-1.png')},
 {id:'coconut-bar',name:'Coconut Bar',kind:'Coconut dessert with coconut pieces',category:'lollies',price:null,img:image('product__0018_Stick-Lolly-Coconut-Bar-Wrapper-768x910-1.png')},
 {id:'custard-jelly',name:'Custard Jelly',kind:'Custard dessert with raspberry ice',category:'lollies',price:null,img:image('product__0017_Stick-Lolly-Custard-Jelly-Wrapper-768x910-1.png')},
 {id:'eish',name:'Eish!',kind:'Fat-free granadilla and apple dessert',category:'lollies',price:null,img:image('product__0016_Stick-Lolly-Eish-Wrapper-768x910-1.png')},
 {id:'grandelch',name:'Grandelch',kind:'Mixed fruit ice',category:'lollies',price:null,img:image('product__0015_Stick-Lolly-Granadelch-Wrapper-768x910-1.png')},
 {id:'granadilla-sherbet',name:'Granadilla Sherbet',kind:'Fat-free granadilla dessert',category:'lollies',price:null,img:image('product__0014_Stick-Lolly-Granadilla-Sherbet-Wrapper-768x910-1.png')},
 {id:'jolly-pine',name:'Jolly Pine',kind:'Pineapple flavoured ice',category:'lollies',price:7,img:image('product__0010_Stick-Lolly-Jolly-Pine-Wrapper-768x910-1.png')},
 {id:'caramello',name:'Caramello',kind:'Vanilla ice cream with caramel crunch',category:'lollies',price:null,img:image('product__0013_Stick-Lolly-Ice-Cream-Caramello-Wrapper-768x910-1.png')},
 {id:'choc99',name:'Choc99',kind:'Strawberry dessert with chocolate and coconut',category:'lollies',price:null,img:image('product__0012_Stick-Lolly-IceCream-Choc99-Wrapper-768x910-1.png')},
 {id:'cocomint',name:'Cocomint',kind:'Mint ice cream in milk chocolate',category:'lollies',price:null,img:image('product__0011_Stick-Lolly-IceCream-Cocomint-Wrapper-768x910-1.png')},
 {id:'just-jelly',name:'Just Jelly',kind:'Raspberry flavoured ice',category:'lollies',price:null,img:image('product__0009_Stick-Lolly-Just-Jelly-3D-Wrapper-768x910-1.png')},
 {id:'icone',name:'iCone',kind:'Vanilla ice cream with chocolate and roasted peanuts',category:'lollies',price:null,img:image('product__0024_iCone-Wrapper-768x910-1.png')},
 {id:'2l-chocolate',name:'2L Chocolate',kind:'Premier chocolate ice cream · 2 litres',category:'tubs',price:90,img:'assets/polar/Premier-2l-Chocolate-Smart-Object-Group-1.png',tag:'2 litre'},
 {id:'2l-strawberry',name:'2L Strawberry',kind:'Premier strawberry ice cream · 2 litres',category:'tubs',price:90,img:'assets/polar/Premier-2l-Strawberry-1.png',tag:'2 litre'},
 {id:'2l-vanilla',name:'2L Vanilla',kind:'Premier vanilla ice cream · 2 litres',category:'tubs',price:90,img:'assets/polar/Premier-2l-Vanilla-1.png',tag:'2 litre'},
 {id:'500-banana-berry',name:'500ml Banana Berry',kind:'Banana and strawberry frozen dessert · 500 ml',category:'tubs',price:35,img:'assets/polar/NJA-500ml-Cup-BananaStrawberry-copy-2.png',tag:'500 ml'},
 {id:'500-choc-mint',name:'500ml Choc Mint',kind:'Chocolate and mint frozen dessert · 500 ml',category:'tubs',price:35,img:'assets/polar/NJA-500ml-Cup-ChocMint-copy-2.png',tag:'500 ml'},
 {id:'500-black-forest',name:'500ml Black Forest',kind:'Chocolate and vanilla with a cherry ripple · 500 ml',category:'tubs',price:35,img:'assets/polar/NJA-500ml-Cup-ChocVanillaCherry-copy-2.png',tag:'500 ml'},
 {id:'500-choc-vanilla',name:'500ml Choc Vanilla Chilla',kind:'Chocolate and vanilla frozen dessert · 500 ml',category:'tubs',price:35,img:'assets/polar/NJA-500ml-Cup-ChocVanilla-copy-2.png',tag:'500 ml'},
 {id:'500-neapolitan',name:'500ml Neapolitan',kind:'Chocolate, vanilla and strawberry frozen dessert · 500 ml',category:'tubs',price:35,img:'assets/polar/NJA-500ml-Cup-ChocVanillaStrawberry.png',tag:'500 ml'},
 {id:'500-strawberry-bubblegum',name:'500ml Strawberry & Bubblegum',kind:'Strawberry and bubblegum frozen dessert · 500 ml',category:'tubs',price:35,img:'assets/polar/NJA-500ml-Cup-StrawberryBubblegum-copy-2.png',tag:'500 ml'},
 {id:'500-vanilla',name:'500ml Vanilla',kind:'Vanilla frozen dessert · 500 ml',category:'tubs',price:35,img:'assets/polar/NJA-500ml-Cup-Vanilla-copy-2.png',tag:'500 ml'},
 {id:'500-vanilla-strawberry',name:'500ml Vanilla Strawberry',kind:'Vanilla and strawberry frozen dessert · 500 ml',category:'tubs',price:35,img:'assets/polar/NJA-500ml-Cup-VanillaStrawberry-copy-2.png',tag:'500 ml'},
 {id:'2l-nja-banana-berry',name:'2L Banana Berry Bliss',kind:'Banana and strawberry frozen dessert · 2 litres',category:'tubs',price:90,img:'assets/polar/NotJustAny-2l-Bananaberry-001-1.png',tag:'2 litre'},
 {id:'2l-nja-choc-mint',name:'2L Cheeky Choc Mint',kind:'Chocolate and mint frozen dessert · 2 litres',category:'tubs',price:90,img:'assets/polar/NotJustAny-2l-Choc-Mint-001-1.png',tag:'2 litre'},
 {id:'2l-nja-choc-nut-sundae',name:'2L Choc Nut Sundae',kind:'Vanilla frozen dessert with chocolate and peanuts · 2 litres',category:'tubs',price:90,img:'assets/polar/NotJustAny-2l-Choc-Nut-Sundae-001-1.png',tag:'2 litre'},
 {id:'2l-nja-chocolate',name:'2L Choc-o-lot',kind:'Chocolate frozen dessert · 2 litres',category:'tubs',price:90,img:'assets/polar/NotJustAny-2l-Chocolate-001-1.png',tag:'2 litre'},
 {id:'2l-nja-choc-vanilla',name:'2L Choc Vanilla Chilla',kind:'Chocolate and vanilla frozen dessert · 2 litres',category:'tubs',price:90,img:'assets/polar/NotJustAny-2l-Choc-Vanilla-001-1.png',tag:'2 litre'},
 {id:'2l-nja-double-caramel',name:'2L Double Caramel',kind:'Caramel dessert with caramel sauce · 2 litres',category:'tubs',price:90,img:'assets/polar/NotJustAny-2l-Double-Caramel-001-1.png',tag:'2 litre'},
 {id:'2l-nja-mint-chip',name:'2L Mint Choc Chip',kind:'Mint dessert with chocolate shavings · 2 litres',category:'tubs',price:90,img:'assets/polar/NotJustAny-2l-Mint-Choc-Chip-001-1.png',tag:'2 litre'},
 {id:'2l-nja-rainbow',name:'2L Rockin’ Rainbow',kind:'Vanilla and strawberry frozen dessert · 2 litres',category:'tubs',price:90,img:'assets/polar/NotJustAny-2l-Rainbow-001-1.png',tag:'2 litre'},
 {id:'2l-nja-rum-raisin',name:'2L Rum & Raisin',kind:'Rum and raisin frozen dessert · 2 litres',category:'tubs',price:90,img:'assets/polar/NotJustAny-2l-Rum-Raisin-001-1.png',tag:'2 litre'},
 {id:'2l-nja-strawberry',name:'2L Seriously Strawberry',kind:'Strawberry frozen dessert · 2 litres',category:'tubs',price:90,img:'assets/polar/NotJustAny-2l-Strawberry-001-1.png',tag:'2 litre'},
 {id:'2l-nja-vanilla-fudge',name:'2L Vanilla Fudge',kind:'Vanilla dessert with chocolate sauce · 2 litres',category:'tubs',price:90,img:'assets/polar/NotJustAny-2l-VanillaFudge-001.png',tag:'2 litre'},

 {id:'polar-pop-orange',name:'Polar Pop Orange',kind:'Orange flavoured ice',category:'lollies',price:null,img:'assets/polar/Polar-Pop-Orange.png',tag:'Polar Pop'},
 {id:'polar-pop-raspberry',name:'Polar Pop Raspberry',kind:'Raspberry flavoured ice',category:'lollies',price:null,img:'assets/polar/Polar-Pop-Raspberry.png',tag:'Polar Pop'},
 {id:'rave-blueberry',name:'Rave Blueberry',kind:'Lemon cheesecake ice cream with blueberry ripple',category:'lollies',price:null,img:'assets/polar/Stick-Lolly-Rave-blueberry-Wrapper-1.png',tag:'Rave'},
 {id:'rave-strawberry',name:'Rave Strawberry',kind:'Vanilla ice cream with strawberry ripple',category:'lollies',price:null,img:'assets/polar/Stick-Lolly-Rave-strawberry-Wrapper-1.png',tag:'Rave'},
 {id:'woza-chocolate',name:'Woza Chocolate',kind:'Chocolate and vanilla ice cream',category:'lollies',price:null,img:'assets/polar/Stick-Lolly-Woza-Lolly-Choc-Wrapper-1.png',tag:'Woza'},
 {id:'woza-strawberry',name:'Woza Strawberry',kind:'Strawberry and vanilla ice cream',category:'lollies',price:null,img:'assets/polar/Stick-Lolly-Woza-Lolly-Strawberry-Wrapper-1.png',tag:'Woza'},
 {id:'maxi-classic',name:'Maxi Classic',kind:'Vanilla ice cream coated in milk chocolate',category:'lollies',price:null,img:'assets/polar/Maxi-Classic.png',tag:'Maxi'},
 {id:'maxi-almond',name:'Maxi Almond',kind:'Vanilla ice cream, milk chocolate and roasted almonds',category:'lollies',price:null,img:'assets/polar/Maxi-Almond.png',tag:'Maxi'},
 {id:'maxi-white-almond',name:'Maxi White Almond',kind:'White chocolate ice cream with roasted almonds',category:'lollies',price:null,img:'assets/polar/Maxi-White-Almond.png',tag:'Maxi'},
 {id:'maxi-ruby-chocolate',name:'Maxi Ruby Chocolate',kind:'Dairy ice cream with black cherry and ruby chocolate',category:'lollies',price:null,img:'assets/polar/Maxi-Ruby-Chocolate.png',tag:'Maxi'},
 {id:'maxi-chocolate-therapy',name:'Maxi Chocolate Therapy',kind:'Chocolate dairy ice cream, sauce and crunchy coating',category:'lollies',price:null,img:'assets/polar/Maxi-Chocolate-Therapy.png',tag:'Maxi'}

];
const rail=document.querySelector('#product-rail');
const money=n=>`R${Number(n).toFixed(2)}`;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cards=(list)=>{rail.innerHTML=list.map(p=>`<article class="product-card" data-category="${p.category}" data-id="${p.id}"><div class="product-image"><span class="product-tag">${esc(p.tag|| (p.category==='tubs'?'FROZEN FAVOURITE':'POLAR RANGE'))}</span><img src="${esc(p.img)}" alt="${esc(p.name)} Polar ice cream packaging" loading="lazy" onerror="this.style.opacity='.15';this.alt='Product image unavailable';this.insertAdjacentHTML('afterend','<span class=\'image-fallback\'>${esc(p.name)}</span>')"></div><div class="product-details"><span class="product-category">${p.category==='tubs'?'TUBS & CUPS':'STICK NOVELTY'}</span><h3>${esc(p.name)}</h3><p class="product-price">${p.price===null?'Ask for price':money(p.price)} <small>${p.price===null?'· confirm on WhatsApp':'· each'}</small></p><div class="product-buy"><div class="qty-control"><button type="button" data-step="-1" aria-label="Decrease ${esc(p.name)} quantity">−</button><input type="number" min="1" value="1" aria-label="${esc(p.name)} quantity"><button type="button" data-step="1" aria-label="Increase ${esc(p.name)} quantity">+</button></div><button class="add-button" type="button" data-add="${p.id}">Add to bag</button></div></div></article>`).join('')};
cards(products);
const cartKey='nmm-holdings-cart-v1';
let cart=JSON.parse(localStorage.getItem(cartKey)||'{}');
const drawer=document.querySelector('.cart-drawer'),scrim=document.querySelector('.cart-scrim'),count=document.querySelector('.cart-count'),items=document.querySelector('.cart-items'),empty=document.querySelector('.cart-empty'),totalEl=document.querySelector('.cart-total strong'),bottom=document.querySelector('.cart-bottom'),toast=document.querySelector('.toast');
const toastMsg=message=>{toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1900)};
const cartCount=()=>Object.values(cart).reduce((n,q)=>n+q,0);
function renderCart(){localStorage.setItem(cartKey,JSON.stringify(cart));count.textContent=cartCount();const entries=products.filter(p=>cart[p.id]);items.innerHTML=entries.map(p=>`<div class="cart-row"><img src="${esc(p.img)}" alt="" loading="lazy"><div><h3>${esc(p.name)}</h3><p>${p.price===null?'Price to confirm':money(p.price)+' each'}</p><div class="cart-row-actions"><button data-cart-step="-1" data-id="${p.id}" aria-label="Remove one">−</button><span>${cart[p.id]}</span><button data-cart-step="1" data-id="${p.id}" aria-label="Add one">+</button></div></div><strong>${p.price===null?'':money(p.price*cart[p.id])}</strong></div>`).join('');empty.style.display=entries.length?'none':'flex';items.style.display=entries.length?'block':'none';bottom.style.display=entries.length?'block':'none';const subtotal=entries.reduce((n,p)=>n+(p.price||0)*cart[p.id],0);totalEl.textContent=money(subtotal)+(entries.some(p=>p.price===null)?'+':'')}
function openCart(){drawer.classList.add('open');drawer.setAttribute('aria-hidden','false');scrim.hidden=false;document.body.classList.add('cart-lock')}
function closeCart(){drawer.classList.remove('open');drawer.setAttribute('aria-hidden','true');scrim.hidden=true;document.body.classList.remove('cart-lock')}
renderCart();
document.addEventListener('click',e=>{const step=e.target.closest('[data-step]');if(step){const input=step.parentElement.querySelector('input');input.value=Math.max(1,(Number(input.value)||1)+Number(step.dataset.step));return}const add=e.target.closest('[data-add]');if(add){const card=add.closest('.product-card'),qty=Math.max(1,Number(card.querySelector('input').value)||1);cart[add.dataset.add]=(cart[add.dataset.add]||0)+qty;renderCart();toastMsg(`${qty} ${qty===1?'item':'items'} added to your bag`);return}const cartStep=e.target.closest('[data-cart-step]');if(cartStep){const id=cartStep.dataset.id;cart[id]=(cart[id]||0)+Number(cartStep.dataset.cartStep);if(cart[id]<=0)delete cart[id];renderCart();return}if(e.target.closest('.cart-open'))openCart();if(e.target.closest('.cart-close')||e.target===scrim)closeCart();if(e.target.closest('.clear-cart')){cart={};renderCart()}if(e.target.closest('.cart-browse'))closeCart();if(e.target.closest('.whatsapp-checkout'))checkout()});
function checkout(){const lines=products.filter(p=>cart[p.id]).map(p=>`• ${p.name} × ${cart[p.id]} — ${p.price===null?'please confirm price':money(p.price*cart[p.id])}`);if(!lines.length)return;const subtotal=products.filter(p=>cart[p.id]&&p.price!==null).reduce((n,p)=>n+p.price*cart[p.id],0);const msg=`Hi Melton, I would like to place an NMM Holdings ice cream order:\n\n${lines.join('\n')}\n\nEstimated subtotal for priced items: ${money(subtotal)}${products.some(p=>cart[p.id]&&p.price===null)?' + items awaiting price confirmation':''}\n\nPlease confirm availability, final price and collection/delivery details.`;window.open(`https://wa.me/27751443192?text=${encodeURIComponent(msg)}`,'_blank','noopener')}
document.querySelectorAll('.filter').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(b=>b.classList.toggle('active',b===btn));const category=btn.dataset.filter;cards(category==='all'?products:products.filter(p=>p.category===category))}));
document.querySelectorAll('[data-scroll]').forEach(btn=>btn.addEventListener('click',()=>rail.scrollBy({left:Number(btn.dataset.scroll)*rail.clientWidth*.8,behavior:'smooth'})));
const menu=document.querySelector('.menu-toggle'),nav=document.querySelector('.main-nav');menu.addEventListener('click',()=>{const active=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(active))});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeCart()});
